<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/27
 * Time: 15:24
 */

namespace app\improve\validate;

class CountryRecord extends BaseValidate
{

    protected $rule = [
        'id'                 => 'require|number',
        'region'             => 'require|max:20',
        'hazard_type'        => 'require|in:1,2,3',
        'pest_id'            => 'require|number',
        'generation'         => 'require|min:1|max:8',
        'tense_age'          => 'max:20',
        'pests_density'      => 'max:16',
        'plant_id'           => 'require|number',
        'harmful_part'       => 'require',
        'strain_rate'        => 'require',
        'hazard_level'       => 'require|in:1,2,3',
        'happen_level'       => 'require|in:1,2,3',
        'harms_level'        => 'require|in:1,2,3',
        'plant_cover_degree' => 'max:16',
        'susceptibility'     => 'require',
        'dead_tree_num'      => 'num|min:0',
        'is_main_pests'      => 'require|in:-1,1',
        'distribution_area'  => 'require|float',
        'damaged_area'       => 'float',
        'positions'          => 'require|positionReg',
        'position_type'      => 'require|in:-1,1,2,3',
        'location_name'      => 'require',
        'ids'                => 'require',
        'del_images'         => 'array|max:6',
        'remarks'            => 'max:20',
        'age'                => 'require',
        'species_type'       => 'require|in:1,2',
        'habitat_type'       => 'require|max:20'
    ];

    protected $message = [
        'region.require'            => '区域必填',
        'region.max'                => '区域最多不能超过20位字符',
        'hazard_type.require'       => '危害类型必填',
        'hazard_type.in'            => '危害类型选择范围错误',
        'pest_id.require'           => '病虫种类必填',
        'pest_id.number'            => '病虫种类格式错误',
        'generation.require'        => '世代必填',
        'generation.min'            => '世代最小为1代',
        'generation.max'            => '世代最多为8代',
        'tense_age.require'         => '时态龄期必填',
        'plant_id.require'          => '寄主树种必填',
        'plant_id.number'           => '寄主树种格式错误',
        'harmful_part.require'      => '危害部位不能为空',
        'hazard_level.require'      => '危害程度必填',
        'hazard_level.in'           => '危害程度选择范围错误',
        'happen_level.require'      => '发生程度必填',
        'happen_level.in'           => '发生程度选择范围错误',
        'plant_cover_degree|max'    => '有害植物覆盖度长度不能超过16位字符',
        'pests_density.max'         => '虫口密度不能超过16位字符',
        'susceptibility.require'    => '感指指数必填',
        'susceptibility.max'        => '感指指数不能超过16位字符',
        'dead_tree_num.number'      => '死树株数必须填数字',
        'dead_tree_num.min'         => '死树株数最小为0',
        'is_main_pests.number'      => '是否是主要病虫害必须为数字',
        'is_main_pests.in'          => '是否是主要病虫害选择范围错误',
        'distribution_area.require' => '分布面积必填',
        'distribution_area.float'   => '分布面积数据格式错误',
        'damaged_area.require'      => '成灾面积必须填数字',
        'damaged_area.float'        => '成灾面积数据格式错误',
        'positions.require'         => '地图位置必填',
        'positions.positionReg'     => '地图位置格式错误',
        'location_name.require'     => '地理位置名称必填',
        'position_type.require'     => '地图位置类型必填',
        'position_type.in'          => '地图位置类型错误',
        'remarks.max'               => '备注长度不能超过20位字符',
        'age.require'               => '龄期不能为空',
        'age.max'                   => '龄期最低为1龄',
        'species_type.require'      => '物种类型不能为空',
        'species_type.in'           => '物种类型选择范围错误',
        'habitat_type.require'      => '生境类型不能为空',
        'habitat_type.max'          => '生境类型长度不能超过20位字符'
    ];

    protected $scene = [
        'disease'      => [
            'region',
            'hazard_type',
            'pest_id',
            'plant_id',
            'happen_level',
            'hazard_level',
            'harmful_part',
            'susceptibility',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'positions',
            'position_type',
            'location_name',
            'remarks',
            'strain_rate'
        ],
        'insect'       => [
            'region',
            'hazard_type',
            'pest_id',
            'plant_id',
            'happen_level',
            'hazard_level',
            'generation',
            'harmful_part',
            'pests_density',
            'strain_rate',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'positions',
            'position_type',
            'location_name',
            'remarks',
        ],
        'plant'        => [
            'region',
            'hazard_type',
            'pest_id',
            'happen_level',
            'hazard_level',
            'plant_cover_degree',
            'habitat_type',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'species_type',
            'positions',
            'position_type',
            'location_name',
            'remarks',
            'strain_rate'
        ],
        'id'           => ['id'],
        'ids'          => ['ids'],
        'disease_edit' => [
            'id',
            'region',
            'hazard_type',
            'pest_id',
            'plant_id',
            'happen_level',
            'hazard_level',
            'harmful_part',
            'susceptibility',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'positions',
            'position_type',
            'remarks',
            'strain_rate'
        ],
        'insect_edit'  => [
            'id',
            'region',
            'hazard_type',
            'pest_id',
            'plant_id',
            'happen_level',
            'hazard_level',
            'generation',
            'harmful_part',
            'tense_age',
            'pests_density',
            'strain_rate',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'positions',
            'position_type',
            'remarks'
        ],
        'plant_edit'   => [
            'id',
            'region',
            'hazard_type',
            'pest_id',
            'hazard_level',
            'plant_cover_degree',
            'habitat_type',
            'is_main_pests',
            'distribution_area',
            'damaged_area',
            'species_type',
            'positions',
            'position_type',
            'remarks',
            'strain_rate'
        ]
    ];

}